## Classifiers: k-NN and Naive Bayes / Exercise 9

In [31]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors

In [21]:
data = pd.read_csv('synthetic_data.txt', sep=',', index_col=0)
data.head()

X   Y  Class
id               
1   42  53      0
2   47  50      0
3   46  69      1
4   33  67      0
5   10  37      0

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 1 to 10
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       10 non-null     int64
 1   Y       10 non-null     int64
 2   Class   10 non-null     int64
dtypes: int64(3)
memory usage: 320.0 bytes


In [23]:
X = data.drop(columns='Class')
y_class = data.Class

### Enter the distance from the new object with coordinates (67, 95) to the nearest neighbor using the Euclidean metric.
### Enter the solution in the form of the decimal fraction rounded to three decimal places.

In [63]:
neigh = NearestNeighbors(n_neighbors=3, metric='euclidean')
neigh.fit(X)
neigh_obj = neigh.kneighbors([[67, 95]])
print(np.round(neigh_obj[0], 3))

[[14.036 29.155 33.422]]


/Users/roman14/.conda/envs/Pycharm/lib/python3.10/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(


### Enter the id of the three nearest points to (67, 95) for the Euclidean metric.
### Enter identifiers separated by commas, spaced away from the point

In [66]:
print(neigh_obj[1] + 1)

[[ 8 10  3]]


### Enter a class for the new object with coordinates (67, 95) given k = 3 for the Euclidean metric.
### Enter class 1 or 0.

In [56]:
knn = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
knn.fit(X, y_class)
knn.predict([[67, 95]])

/Users/roman14/.conda/envs/Pycharm/lib/python3.10/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1])

### Enter the distance from the new object with coordinates (67, 95) to the nearest neighbor using the Manhattan distance.
### Enter the solution in the form of the decimal fraction rounded to three decimal places.

In [67]:
neigh = NearestNeighbors(n_neighbors=3, metric='manhattan')
neigh.fit(X)
neigh_obj = neigh.kneighbors([[67, 95]])
print(np.round(neigh_obj[0], 3))

[[15. 40. 40.]]


/Users/roman14/.conda/envs/Pycharm/lib/python3.10/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(


### Enter the id of the three nearest points to (67, 95) for the Manhattan distance.
### Enter identifiers separated by commas, spaced away from the point (67, 95).

In [68]:
print(neigh_obj[1] + 1)

[[ 8 10  9]]


### Enter a class for the new object with coordinates (67, 95) given k = 3 for the Manhattan distance.
### Enter class 1 or 0.

In [60]:
knn = KNeighborsClassifier(n_neighbors=3, metric='manhattan')
knn.fit(X, y_class)
knn.predict([[67, 95]])

/Users/roman14/.conda/envs/Pycharm/lib/python3.10/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0])