# Import libraries

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
from collections import defaultdict
import timeit
from tqdm import tqdm
from scipy.sparse.csgraph import dijkstra
from scipy.sparse.csgraph import bellman_ford

# Formulation of the problem and methods
### I.	Generate a random adjacency matrix for a simple undirected weighted graph of 100 vertices and 500 edges with assigned random positive integer weights (note that the matrix should be symmetric and contain only 0s and weights as elements). Use Dijkstra's and Bellman-Ford algorithms to find shortest paths between a random starting vertex and other vertices. Measure the time required to find the paths for each algorithm. Repeat the experiment 10 times for the same starting vertex and calculate the average time required for the paths search of each algorithm. Analyse the results obtained.
### II.	Generate a 10x20 cell grid with 40 obstacle cells. Choose two random non-obstacle cells and find a shortest path between them using A* algorithm. Repeat the experiment 5 times with different random pair of cells. Analyse the results obtained.
### III.	Describe the data structures and design techniques used within the algorithms.

# Part 1

In [9]:
# Generate a random symmetric adjacency matrix
# squared matrix is symmetric if a(i, j) == a(j, i) or M = M^T

n_vertices = 100
n_edges = 500

def make_symmetric_adjency_matrix(n_vertices, n_edges):
    matrix = np.random.randint(50, size=(n_vertices, n_vertices))
    np.fill_diagonal(matrix, 0)

    matrix = np.matmul(matrix, matrix.T)

    return matrix

adj_matrix = make_symmetric_adjency_matrix(n_vertices, n_edges)
print('Is matrix symmetric:', np.array_equal(adj_matrix, adj_matrix.transpose()), '\n',
      'Is matrix squared: ', adj_matrix.shape, '\n', 'Matrix:', adj_matrix)

Is matrix symmetric: True 
 Is matrix squared:  (100, 100) 
 Matrix: [[66462 53235 52726 ... 49300 48629 54407]
 [53235 82032 59600 ... 55453 58467 61249]
 [52726 59600 76295 ... 57391 55361 59738]
 ...
 [49300 55453 57391 ... 81980 52229 60691]
 [48629 58467 55361 ... 52229 75417 55979]
 [54407 61249 59738 ... 60691 55979 84906]]


In [10]:
N = 100
V = 500
b = np.zeros(shape=(N,N))
upper_triangle = np.triu_indices(N,1)

indexes = np.arange(0, len(upper_triangle[0]))
indexes = np.random.choice(indexes, V, replace=False)

for i in indexes:
    idx1 = upper_triangle[0][i]
    idx2 = upper_triangle[1][i]
    b[idx1,idx2] = np.random.randint(0, 100)

adj_matrix = (b + b.T)

In [11]:
adj_list = defaultdict(list)

for i in range(N):
    for j in range(N):
        adj_list[i].append(j) if adj_matrix[i, j] != 0 else next

In [18]:
G = nx.from_numpy_array(adj_matrix)

In [19]:
def get_execution_time(algorithm, G, array):
    start_time = timeit.default_timer()

    algorithm(G, array[0], array[1])

    return timeit.default_timer() - start_time

In [22]:
def get_execution_time_array(algorithm, G, array, mean_count=10):
    execution_time_summ = 0
    for m in range(mean_count):
        execution_time_summ += get_execution_time(algorithm, G, array)

    execution_time_mean = execution_time_summ / mean_count

    return execution_time_mean

In [28]:
array = np.random.randint(0, 100, size=2)
dijkstra_mean_time = get_execution_time_array(nx.dijkstra_path, G, array)
bellman_ford_mean_time = get_execution_time_array(nx.bellman_ford_path, G, array)
print("Dijkstra algorithm execution mean time - {:.5f}".format(dijkstra_mean_time),
      f'(between vertices {array[0]} and {array[1]}, path - {nx.dijkstra_path(G, array[0], array[1])})', '\n'
      "Bellman-Ford algorithm execution mean time - {:.5f}".format(bellman_ford_mean_time),
      f'(between vertices {array[0]} and {array[1]}, path - {nx.bellman_ford_path(G, array[0], array[1])})')

Dijkstra algorithm execution mean time - 0.00039 (between vertices 33 and 31, path - [33, 43, 24, 51, 52, 31]) 
Bellman-Ford algorithm execution mean time - 0.00057 (between vertices 33 and 31, path - [33, 43, 24, 51, 52, 31])


In [ ]:
nx.dijkstra_path

# Part 2

# Conclusion